# Site wide configuration

title: MSDSE
description: "Enabing data-driven academic research"
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: blog-cover.jpg # 400x250 px default teaser image used in image archive grid
locale:
url: http://msdse.org

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
plugins:
  - jekyll-redirect-from

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: # bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
